//let b = 2;

try {

  let a = 2 + b;

} catch(erro) {

  console.log("Algo n√£o deu Certo: "+ erro);

} finally {

  console.log("[Finalmente] Executou");

}

// console.log('teste');